name: notify problem

on:
  schedule:
    - cron: '30 0 * * 1,2,3,4,5'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Notify yesterday reward
      run: |
          python src/reward.py "$SLACK_API2"
      env:
          SLACK_API2: ${{ secrets.SLACK_API2 }}
    
    - name: Remove old data
      run: |
        rm src/yesterday.txt
        git config user.name "<git-user-name>"
        git config user.email "<git-user-e-mail>"
        git add *
        git commit -m "Update"
        git push origin master

    - name: Notify today problem
      run: |
          python src/test.py "$SLACK_API"
      env:
          SLACK_API: ${{ secrets.SLACK_API }}
    
    - name: Save today priblem
      run: |
        git config user.name "<git-user-name>"
        git config user.email "<git-user-e-mail>"
        git add *
        git commit -m "Update"
        git push origin master